SYSTEM_NAME="bbc"
SYSTEM_FULLNAME="BBC Micro"
SYSTEM_MANUFACTURER="Acorn"
SYSTEM_RELEASE="1981"
SYSTEM_HARDWARE="computer"
SYSTEM_PATH="/storage/roms/bbc"
SYSTEM_EXTENSION=".ssd .dsd"
SYSTEM_PLATFORM="bbc"
SYSTEM_THEME="bbc"
SYSTEM_WIKI_PATH="bbc"
