name: Fail on upstream packages changes

on:
  pull_request:
    paths:
      - 'packages/**'

jobs:
  check-upstream-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if upstream packages changed
        run: |
          echo "Detected changes in upstream packages folder. Failing the job."
          exit 1